config/routes.rb
Active::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :buses

  root :to => 'buses#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  attr_accessible :age, :bus_name, :phone_number, :image, :remote_image_url
   mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buses }
    end
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
    @bus = Bus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bus }
    end
  end

  # GET /buses/new
  # GET /buses/new.json
  def new
    @bus = Bus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bus }
    end
  end

  # GET /buses/1/edit
  def edit
    @bus = Bus.find(params[:id])
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(params[:bus])

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render json: @bus, status: :created, location: @bus }
      else
        format.html { render action: "new" }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buses/1
  # PUT /buses/1.json
  def update
    @bus = Bus.find(params[:id])

    respond_to do |format|
      if @bus.update_attributes(params[:bus])
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy

    respond_to do |format|
      format.html { redirect_to buses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.erb
<%= form_for @bus, :html => {:multipart => true} do |f| %>
  <% if @bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% @bus.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bus_name %><br />
    <%= f.text_field :bus_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing bus</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<h1>Listing buses</h1>

<table>
  <tr>
    <th>Bus name</th>
    <th>Age</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buses.each do |bus| %>
  <tr>
    <td><%= bus.bus_name %></td>
    <td><%= bus.age %></td>
    <td><%= bus.phone_number %></td>
    <td><%= link_to 'Show', bus %></td>
    <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
    <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New bus</h1>

<%= render 'form' %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<%= image_tag @bus.image_url(:thumb) if @bus.image? %>
<p id="notice"><%= notice %></p>

<p>
  <b>Bus name:</b>
  <%= @bus.bus_name %>
</p>

<p>
  <b>Age:</b>
  <%= @bus.age %>
</p>

<p>
  <b>Phone number:</b>
  <%= @bus.phone_number %>
</p>


<%= link_to 'Edit', edit_bus_path(@bus) %> |
<%= link_to 'Back', buses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Active</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>